[package]
name = "carbon-jupiter-swap-decoder"
version = "0.3.1"
description = "Jupiter Swap Decoder"
license = "MIT"
edition = "2018"

[lib]
crate-type = ["rlib"]

[dependencies]
carbon-core = { workspace = true }
solana-sdk = "2.0.10"
serde = "1.0.136"
