[workspace]
# TODO: Add examples back
members = [
    "crates/*",
    "datasources/*",
    "decoders/*",
    "metrics/*",
    "examples/*",
    "libs/*",
]
resolver = "2"

[workspace.dependencies]
carbon-core = { path = "crates/core", version = "0.1.0" }
carbon-macros = { path = "crates/macros", version = "0.1.0" }
carbon-proc-macros = { path = "crates/proc-macros", version = "0.1.0" }
carbon-rpc-program-subscribe-datasource = { path = "datasources/rpc-program-subscribe-datasource", version = "0.1.0" }
log-metrics = { path = "metrics/log-metrics", version = "0.1.0" }
carbon-cli = { path = "crates/cli", version = "0.1.0" }
solana-sdk = "=2.0.10"
solana-transaction-status = "=2.0.10"
solana-client = "=2.0.10"

[patch.crates-io.curve25519-dalek]
git = "https://github.com/anza-xyz/curve25519-dalek.git"
rev = "b500cdc2a920cd5bff9e2dd974d7b97349d61464"
