[package]
name = "carbon-pumpfun-decoder"
version = "0.6.1"
description = "Pumpfun Decoder"
license = { workspace = true }
edition = { workspace = true }
readme = "README.md"
repository = { workspace = true }
keywords = ["solana", "decoder", "pumpfun"]
categories = ["encoding"]

[lib]
crate-type = ["rlib"]

[dependencies]
carbon-core = { workspace = true }
serde = { workspace = true }
solana-sdk = { workspace = true }

[dev-dependencies]
carbon-test-utils = { workspace = true }
