[package]
name = "carbon-yellowstone-grpc-datasource"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["rlib"]

[dependencies]
tokio = { version = "1.40.0", features = ["full"] }
async-trait = "0.1.83"
carbon-core = { path = "../../crates/core" }
solana-client = "2.0.10"
solana-sdk = "=2.0.10"
solana-transaction-status = "2.0.9"
log = "0.4.22"
env_logger = "0.11.5"
yellowstone-grpc-proto = { version = "=1.15.0+solana.2.0.10", default-features = false, git = "https://github.com/rpcpool/yellowstone-grpc.git" }   