[package]
name = "raydium-cpmm-alerts-carbon-example"
version = "0.1.0"
edition = "2021"

[dependencies]
carbon-core = { workspace = true }
solana-sdk = { workspace = true }
solana-transaction-status = { workspace = true }
solana-client = { workspace = true }
carbon-log-metrics = { workspace = true }
carbon-raydium-cpmm-decoder = { workspace = true }
carbon-rpc-block-subscribe-datasource = { workspace = true }

tokio = { workspace = true, features = ["full"] }
async-trait = { workspace = true }
log = "0.4.22"
env_logger = "0.11.5"
dotenv = "0.15.0"
