[package]
name = "carbon-mpl-core-decoder"
version = "0.2.1"
description = "MPL Core Decoder"
license = "MIT"
edition = "2018"

[lib]
crate-type = ["rlib"]

[dependencies]
carbon-core = { workspace = true }
solana-sdk = "2.0.10"
serde = "1.0.136"
