[package]
name = "carbon-mpl-core-decoder"
version = "0.4.1"
description = "MPL Core Decoder"
license = { workspace = true }
edition = { workspace = true }

[lib]
crate-type = ["rlib"]

[dependencies]
carbon-core = { workspace = true }
serde = { workspace = true }
solana-sdk = { workspace = true }
