[package]
name = "carbon-jupiter-limit-order-2-decoder"
version = "0.1.2"
description = "Jupiter Limit Order 2 Decoder"
license = "MIT"
edition = "2018"

[lib]
crate-type = ["rlib"]

[dependencies]
carbon-core = "0.1.1"
carbon-proc-macros = "0.1.1"
carbon-macros = "0.1.1"

solana-sdk = "2.0.10"
serde = "1.0.136"
