[package]
name = "carbon-jupiter-limit-order-2-decoder"
version = "0.5.1"
description = "Jupiter Limit Order 2 Decoder"
license = { workspace = true }
edition = { workspace = true }

[lib]
crate-type = ["rlib"]

[dependencies]
carbon-core = { workspace = true }
serde = { workspace = true }
solana-sdk = { workspace = true }
