[package]
name = "carbon-jupiter-limit-order-2-decoder"
version = "0.6.2"
description = "Jupiter Limit Order 2 Decoder"
license = { workspace = true }
edition = { workspace = true }
readme = "README.md"
repository = { workspace = true }
keywords = ["solana", "decoder", "jupiter", "limit-order"]
categories = ["encoding"]

[lib]
crate-type = ["rlib"]

[dependencies]
carbon-core = { workspace = true }
serde = { workspace = true }
solana-sdk = { workspace = true }
