[package]
name = "carbon-meteora-pools-decoder"
version = "0.6.2"
description = "Meteora Pools Program Decoder"
license = { workspace = true }
edition = { workspace = true }
readme = "README.md"
repository = { workspace = true }
keywords = ["solana", "decoder", "meteora-pools"]
categories = ["encoding"]

[lib]
crate-type = ["rlib"]

[dependencies]
carbon-core = { workspace = true }
serde = { workspace = true }
solana-sdk = { workspace = true }
serde-big-array = { workspace = true }

[dev-dependencies]
carbon-test-utils = { workspace = true }
