[package]
name = "rpc-transaction-crawler-test"
version = "0.1.0"
edition = "2018"

[dependencies]
carbon-rpc-transaction-crawler-datasource = { path = "../../datasources/rpc-transaction-crawler-datasource"}
tokio = { version = "1.40.0", features = ["full"] }
async-trait = "0.1.83"
carbon-core = { path = "../../crates/core" }
carbon-macros = { path = "../../crates/macros" }
carbon-proc-macros = { path = "../../crates/proc-macros" }
solana-client = "2.0.10"
solana-sdk = "2.0.10"
solana-transaction-status = "2.0.9"
log = "0.4.22"
env_logger = "0.11.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
once_cell = "1.17.1"
futures = "0.3.30"
paste = "1.0.15"



