[package]
name = "carbon-token-program-decoder"
version = "0.6.0"
description = "Token Program Decoder"
license = { workspace = true }
edition = { workspace = true }
readme = "./README.md"
repository = { workspace = true }

[lib]
crate-type = ["rlib"]

[dependencies]
carbon-core = { workspace = true }
serde = { workspace = true }
solana-sdk = { workspace = true }
spl-token = { workspace = true }
