[package]
name = "carbon-token-program-decoder"
version = "0.2.1"
description = "Token Program Decoder"
license = "MIT"
edition = "2018"

[lib]
crate-type = ["rlib"]

[dependencies]
carbon-core = "0.2.1"
solana-sdk = "2.0.10"
serde = "1.0.136"
spl-token = "6.0.0"
