[package]
name = "carbon-pump-swap-decoder"
version = "0.6.2"
description = "PumpSwap Decoder"
license = { workspace = true }
edition = { workspace = true }
readme = "README.md"
repository = { workspace = true }
keywords = ["solana", "decoder", "pump-swap"]
categories = ["encoding"]

[lib]
crate-type = ["rlib"]

[dependencies]
carbon-core = { workspace = true }
serde = { workspace = true }
solana-sdk = { workspace = true }

[dev-dependencies]
carbon-test-utils = { workspace = true }
