[package]
name = "carbon-proc-macros"
version = "0.1.0"
edition = "2018"

[dependencies]
carbon-core = { workspace = true }
solana-sdk = { workspace = true }
solana-transaction-status = { workspace = true }
solana-client = { workspace = true }

syn = { version = "1.0", features = ["full"] }
paste = "1.0.15"
quote = "1.0"
hex = "0.4.3"

[lib]
crate-type = ["proc-macro"]
