[package]
name = "carbon-proc-macros"
version = "0.1.0"
edition = "2018"

[dependencies]
carbon-core = { path = "../core" }
hex = "0.4.3"
paste = "1.0.15"
quote = "1.0"
syn = { version = "1.0", features = ["full"] }
solana-sdk = "=2.0.10"

[lib]
crate-type = ["proc-macro"]
