[package]
name = "carbon-jupiter-dca-decoder"
version = "0.1.4"
description = "Jupiter DCA Decoder"
license = "MIT"
edition = "2018"

[lib]
crate-type = ["rlib"]

[dependencies]
carbon-core = "0.1.4"
carbon-proc-macros = "0.1.4"
carbon-macros = "0.1.4"

solana-sdk = "2.0.10"
serde = "1.0.136"
