[package]
name = "carbon-jupiter-dca-decoder"
version = "0.5.1"
description = "Jupiter DCA Decoder"
license = { workspace = true }
edition = { workspace = true }
readme = "./README.md"
repository = { workspace = true }

[lib]
crate-type = ["rlib"]

[dependencies]
carbon-core = { workspace = true }

serde = { workspace = true }
solana-sdk = { workspace = true }

[dev-dependencies]
carbon-test-utils = { workspace = true }