[package]
name = "carbon-lifinity-amm-v2-decoder"
version = "0.6.1"
description = "Lifinity AMM V2 Decoder"
edition = { workspace = true }
license = { workspace = true }
readme = "README.md"
repository = { workspace = true }
keywords = ["solana", "decoder", "lifinity"]
categories = ["encoding"]

[lib]
crate-type = ["rlib"]

[dependencies]
carbon-core = { workspace = true }
carbon-macros = { workspace = true }
carbon-proc-macros = { workspace = true }
serde = { workspace = true }
solana-sdk = { workspace = true }

[dev-dependencies]
carbon-test-utils = { workspace = true }
