[package]
name = "carbon-macros"
version = "0.1.0"
edition = "2018"
description = "Macros for Carbon"
license = "MIT"

[dependencies]
carbon-core = { workspace = true }
solana-transaction-status = "=2.0.10"
solana-client = "=2.0.10"
solana-sdk = "=2.0.10"

hex = "0.4.3"
paste = "1.0.15"

[lib]
crate-type = ["rlib"]
