[package]
name = "carbon-macros"
version = "0.1.0"
edition = "2018"

[dependencies]
carbon-core = { workspace = true }
solana-sdk = { workspace = true }
solana-transaction-status = { workspace = true }
solana-client = { workspace = true }

hex = "0.4.3"
paste = "1.0.15"

[lib]
crate-type = ["rlib"]
