[package]
name = "sharky-offers-carbon-example"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0.89"
async-trait = "0.1.83"
carbon-core = { workspace = true }
carbon-macros = { workspace = true }
carbon-proc-macros = { workspace = true }
carbon-rpc-program-subscribe-datasource = { workspace = true }
log-metrics = { workspace = true }
serde = { version = "1.0.210", features = ["derive"] }
solana-client.workspace = true
solana-sdk.workspace = true
tokio = { version = "1.40.0", features = ["full"] }
tokio-util = "0.7.12"
dotenv = "0.15.0"