[package]
name = "carbon-system-program-decoder"
version = "0.1.52"
description = "System Program Decoder"
license = "MIT"
edition = "2018"

[lib]
crate-type = ["rlib"]

[dependencies]
carbon-core = "0.1.52"
carbon-proc-macros = "0.1.52"
carbon-macros = "0.1.52"

solana-sdk = "2.0.10"
serde = "1.0.136"
spl-token = "6.0.0"
