[package]
name = "carbon-system-program-decoder"
version = "0.7.0"
description = "System Program Decoder"
license = { workspace = true }
edition = { workspace = true }
readme = "README.md"
repository = { workspace = true }
keywords = ["solana", "decoder", "system"]
categories = ["encoding"]

[lib]
crate-type = ["rlib"]

[dependencies]
carbon-core = { workspace = true }
serde = { workspace = true }
solana-sdk = { workspace = true }
spl-token = { workspace = true }

[dev-dependencies]
carbon-test-utils = { workspace = true }
